name: Deploy React app to AWS using CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t vikta96/react-js:new .

    - name: Push Docker image
      run: docker push vikta96/react-js:new

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy1.zip . -x '.git'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: demo
          environment_name: Demo-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-961150958852
          region: ap-southeast-2
          deployment_package: deploy1.zip 
