
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.1]
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      - name: Generate Deployment Package 
        run: zip -r newapp.zip * -x "**.git**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          # replaces '[:\.]+' in the timestamp with '-'
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          application_name: newapp
          environment_name: newapp-env
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: ap-south-1
          deployment_package: newapp.zip
